name: ci/cd ecommerce-cloud

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ecommerce-cloud

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Sesuaikan dengan Node.js yang kamu pakai di EC2

    - name: Install dependencies
      run: |
        cd ecommerce-cloud
        npm install

    - name: Run unit tests
      run: |
        cd ecommerce-cloud
        npm test || echo "No test scripts, continue" 
        # supaya kalau tidak ada npm test, workflow tetap lanjut

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: ecommerce-cloud

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/ecommerce-cloud
          git pull origin main
          npm install
          pm2 restart ecommerce-app

